# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: ["main"]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v3
      with:
        clean: false

    - name: Install Emscripten
      # Clone the Emscripten SDK repository, install tools and activate.
      # See: https://emscripten.org/docs/getting_started/downloads.html
      run: |
        cd ..
        git clone https://github.com/emscripten-core/emsdk.git
        emsdk/emsdk install latest
        emsdk/emsdk activate latest

    - name: Configure CMake and Build
      # Source environment variables from 'emsdk_env.sh' to use 'emcmake' and 'emmake'.
      # Using 'emcmake', configure CMake in a 'build' subdirectory and then run 'emmake'.
      run: |
        source ../emsdk/emsdk_env.sh
        emcmake cmake -B build
        emmake make -C build

    - name: Upload GitHub Pages Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ${{github.workspace}}/build/dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
